export const SET_DEPARTMENTLIST = 'SET_DEPARTMENTLIST'  //departmentList
export const SET_SELECTDEPARTMENTLIST = 'SET_SELECTDEPARTMENTLIST'  //selectDepartmentList
export const SET_SELECTDEPARTMENTUSERLIST = 'SET_SELECTDEPARTMENTUSERLIST'  //selectDepartmentUserList

export const LOGIN = 'LOGIN'


export const LOGIN_ACCOUNT = 'LOGIN_ACCOUNT';
export const ADDUSERANSWERDATA = 'ADDUSERANSWERDATA'
export const USERLOCALLOGIN = 'USERLOCALLOGIN';



